#! /bin/bash

source .env
clear
echo """
=========================
Building React Bundle
Basehref: /$BASE_HREF
Output: build-$BASE_HREF
=========================
"""
PUBLIC_URL="/$BASE_HREF" REACT_APP_BASE_HREF="/$BASE_HREF" npm run build
rsync -a build/ "build-$BASE_HREF/"

echo "Uploading..."
cmd="rsync -avzd $PWD/build-$BASE_HREF/ $LINUX_USER@$LINUX_HOST:/home/$LINUX_USER/$BASE_HREF/"
eval $cmd
echo $cmd

echo """
=========================
Done. Deployed to:
https://$LINUX_HOST/$BASE_HREF
=========================
"""
