#! /bin/bash

echo -e """ \033[32m
===========================
DEPLOYING BUNDLES TO GITHUB
BASE_HREF : \033[36m${BASE_HREF} \033[32m
=========================== \033[0m
"""

source .env
BASE_HREF="/$GITHUB_REPO_NAME/"

# Build pages for github deployment
PUBLIC_URL="/$BASE_HREF" REACT_APP_BASE_HREF="/$BASE_HREF" npm run build


node -e '''
  const ghpages = require("gh-pages");

  const GITHUB_USER_NAME = "dwd-umd";
  const GITHUB_REPO_NAME = "pdco-dashboard";

  console.log("DEPLOYING...");

  ghpages.publish("build-github", function (err) {
    if (!!err) {
      console.log(`OH NO! STH WENT WRONG :(`, err);
      process.exit(1);
    }
    console.log(`DEPLOYED TO: https://${GITHUB_USER_NAME}.github.io/${GITHUB_REPO_NAME}/`);
  })
'''

echo -e """ \033[32m
==========================================================
Done. Your page has been deployed to:\033[36m
https://"$GITHUB_USER_NAME".github.io/"$GITHUB_REPO_NAME"/ \033[32m
========================================================== \033[0m
"""
